### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by alejandrojapkin** [jonashackt/docker-ci-stack#13]
Testing the project, it looks solid and it's a very promising start to produce a gitlab learning lab. Unfortunately, your README is all over the place, the wording is confusing, superfluous anecdotes and  missing steps. It's fantastic that a "why not just docker" section is included (that's great, few people explain architecture choices and that's critical!) but it doesn't properly explain anything, and then the installation steps and pipeline descriptions are cumbersome to follow through, so your documentation rarely will end up in reproducible knowledge.

**Suggestions**:

1. The wording and steps provided.
2. Universalize the README so that it doesn't rely on the user owning a domain or doing this remotely. Your script looks like a lab and labs will often be deployed in.. _labs_, locally.
3. You're teaching people how to build a Gitlab webservice thus defeating the purpose of Gitlab altogether. Your scripts are solid enough to guide someone to deploy pure infrastructure as code and thus having no steps involving the Gitlab web UI, this is otherwise squandering the best part of your effort and what makes Gitlab unique at the same time: that it can all be managed through code.

**Comment by jonashackt** [comment]
Thanks @datascienceteam01 for your in-depth feedback. You're right, the README is confusing - but it's also intended, though not documented that it is. I provide a fully comprehensible documentation in this blog post (which is linked at the top of the project): https://blog.codecentric.de/en/2018/05/gitlab-ci-pipeline/
The README is only my "write things down" thing, while I'am actually building and coding this project. I don't have a step after using the project for my blog, that should refactor the readme. That's mainly due to not having the time - but also I don't want to loose my thoughts I initially had. So I don't really have a solution here - although you're absolutely right in many points.

Just a side-note on the domain you need to own: This is something I had to learn hard, because GitLab is all build around this fact - owning your own domain. You could - to some point - move through the steps without using a domain, just by using `localhost`. But really soon you'll run into troubles! Docker won't work, the Registry neither, your Browser will complain all the time... So I don't think, leaving out the domain is an option. That was all the point I needed to find a way of using a domain also locally - incl. all the Let's Encrypt magic having __no online server__. But this is fixed - it's not nice, but this is a design decision made by GitLab folks. They just don't emphasise this enough in their docs IMHO.
